# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst

research_task:
  description: >
    Conduct thorough research on {topic}, including academic papers, web articles, and recent developments.
    Ensure information is relevant given the current year is {current_year}.
  expected_output: >
    A list of 10-15 bullet points summarizing the most important and relevant information about {topic}.
  agent: researcher

fact_check_task:
  description: >
    Verify the accuracy of each item from the research output.
    Confirm that all claims are supported by reliable sources and remove any incorrect or misleading information.
  expected_output: >
    A cleaned and validated list of bullet points where all facts are confirmed and reliable.
  agent: fact_checker

summarize_task:
  description: >
    Condense the verified research findings into a coherent and structured summary.
    Organize information into main points and subpoints for easier understanding.
  expected_output: >
    A clear, concise summary of the topic that highlights the main ideas and key details.
  agent: summarizer

write_report_task:
  description: >
    Convert the summarized information into a full research report.
    Structure it with headings, sections, and subpoints. Make it professional and readable.
    Format the report in markdown without using code blocks.
  expected_output: >
    A complete report with structured sections, headings, and detailed explanations.
    Ready for review or publication.
  agent: writer

review_report_task:
  description: >
    Review the final report for grammar, clarity, formatting, and completeness.
    Make sure the report is easy to read, professional, and free from mistakes.
  expected_output: >
    The final polished report with any corrections applied and suggestions implemented.
    Ready to be shared or submitted.
  agent: reviewer
